/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 14:16:58 GMT 2018
 */

package ServerPart;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ServerPart.Accepter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteLocalAddress;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Accepter_ESTest extends Accepter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Accepter accepter0 = new Accepter(2512);
      accepter0.run();
      accepter0.run();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Accepter accepter0 = new Accepter(0);
      accepter0.run();
      EvoSuiteLocalAddress evoSuiteLocalAddress0 = new EvoSuiteLocalAddress("192.168.1.42", 40005);
      NetworkHandling.sendDataOnTcp(evoSuiteLocalAddress0, (byte[]) null);
      accepter0.run();
      accepter0.run();
      accepter0.run();
      accepter0.run();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Accepter accepter0 = new Accepter((-957));
      // Undeclared exception!
      try { 
        accepter0.run();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Port value out of range: -957
         //
         verifyException("org.evosuite.runtime.mock.java.net.MockServerSocket", e);
      }
  }
}
