/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 14:12:38 GMT 2018
 */

package ServerPart;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ServerPart.Chat;
import ServerPart.Connection;
import java.net.Socket;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockSocket;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Connection_ESTest extends Connection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockSocket mockSocket0 = new MockSocket();
      Chat chat0 = new Chat();
      Connection connection0 = new Connection(mockSocket0, chat0);
      connection0.run();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Chat chat0 = new Chat();
      Connection connection0 = new Connection((Socket) null, chat0);
      // Undeclared exception!
      try { 
        connection0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ServerPart.Connection", e);
      }
  }
}
