/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 14:16:08 GMT 2018
 */

package ServerPart;

import org.junit.Test;
import static org.junit.Assert.*;
import ServerPart.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User(0, "fAmMmG]DFnL}lNR");
      user0.setNickname((String) null);
      user0.getNickname();
      assertEquals(0, user0.getId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User(0, "fAmMmG]DFnL}lNR");
      user0.setNickname("");
      user0.getNickname();
      assertEquals(0, user0.getId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      User user0 = new User(0, "fAmMmG]DFnL}lNR");
      int int0 = user0.getId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      User user0 = new User(1, (String) null);
      int int0 = user0.getId();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      User user0 = new User((-227), "Gj=4.8Czwn.|zxn!)g=");
      user0.getNickname();
      assertEquals((-227), user0.getId());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      User user0 = new User((-227), "Gj=4.8Czwn.|zxn!)g=");
      user0.setId((-227));
      assertEquals((-227), user0.getId());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      User user0 = new User((-227), "Gj=4.8Czwn.|zxn!)g=");
      int int0 = user0.getId();
      assertEquals((-227), int0);
  }
}
