/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 14:12:00 GMT 2018
 */

package ClientPart;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ClientPart.ClientConnector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteRemoteAddress;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClientConnector_ESTest extends ClientConnector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteRemoteAddress evoSuiteRemoteAddress0 = new EvoSuiteRemoteAddress("127.0.0.1", 9);
      NetworkHandling.openRemoteTcpServer(evoSuiteRemoteAddress0);
      ClientConnector clientConnector0 = new ClientConnector(9);
      clientConnector0.connect();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClientConnector clientConnector0 = new ClientConnector(0);
      clientConnector0.connect();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClientConnector clientConnector0 = new ClientConnector((-3639));
      // Undeclared exception!
      try { 
        clientConnector0.connect();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // port out of range:-3639
         //
         verifyException("java.net.InetSocketAddress", e);
      }
  }
}
