/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 14:14:52 GMT 2018
 */

package ClientPart;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ClientPart.MessageReceiver;
import java.io.ObjectInputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MessageReceiver_ESTest extends MessageReceiver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageReceiver messageReceiver0 = new MessageReceiver((ObjectInputStream) null);
      // Undeclared exception!
      try { 
        messageReceiver0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ClientPart.MessageReceiver", e);
      }
  }
}
